/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.scoping.ui.internal.ScopingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScopingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ScopingActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ScopingActivator activator = ScopingActivator.getInstance();
		return activator != null ? activator.getInjector(ScopingActivator.ORG_XTEXT_EXAMPLE_SCOPING_SCOPING) : null;
	}

}
