/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.scoping.scoping.Book;
import org.xtext.example.scoping.scoping.Chapter;
import org.xtext.example.scoping.scoping.DImport;
import org.xtext.example.scoping.scoping.Paragraph;
import org.xtext.example.scoping.scoping.Reference;
import org.xtext.example.scoping.scoping.ScopingPackage;
import org.xtext.example.scoping.services.ScopingGrammarAccess;

@SuppressWarnings("all")
public class ScopingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ScopingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ScopingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ScopingPackage.BOOK:
				sequence_Book(context, (Book) semanticObject); 
				return; 
			case ScopingPackage.CHAPTER:
				sequence_Chapter(context, (Chapter) semanticObject); 
				return; 
			case ScopingPackage.DIMPORT:
				sequence_DImport(context, (DImport) semanticObject); 
				return; 
			case ScopingPackage.PARAGRAPH:
				sequence_Paragraph(context, (Paragraph) semanticObject); 
				return; 
			case ScopingPackage.REFERENCE:
				sequence_Reference(context, (Reference) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Book returns Book
	 *
	 * Constraint:
	 *     (name=QualifiedName imports+=DImport* chapters+=Chapter*)
	 */
	protected void sequence_Book(ISerializationContext context, Book semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Chapter returns Chapter
	 *
	 * Constraint:
	 *     (name=ID (chapter+=Chapter | paragraphs+=Paragraph | references+=Reference)*)
	 */
	protected void sequence_Chapter(ISerializationContext context, Chapter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DImport returns DImport
	 *
	 * Constraint:
	 *     importedNamespace=QualifiedNameWithWildcard
	 */
	protected void sequence_DImport(ISerializationContext context, DImport semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ScopingPackage.Literals.DIMPORT__IMPORTED_NAMESPACE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ScopingPackage.Literals.DIMPORT__IMPORTED_NAMESPACE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDImportAccess().getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0(), semanticObject.getImportedNamespace());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Paragraph returns Paragraph
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Paragraph(ISerializationContext context, Paragraph semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ScopingPackage.Literals.PARAGRAPH__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ScopingPackage.Literals.PARAGRAPH__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParagraphAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Reference returns Reference
	 *
	 * Constraint:
	 *     (cref=[Chapter|ID] | qnref=[Chapter|QualifiedName] | pref=[Paragraph|ID])
	 */
	protected void sequence_Reference(ISerializationContext context, Reference semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
