/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping;

import org.xtext.example.scoping.AbstractScopingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ScopingRuntimeModule extends AbstractScopingRuntimeModule {
}
