/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping;

import org.xtext.example.scoping.ScopingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ScopingStandaloneSetup extends ScopingStandaloneSetupGenerated {
  public static void doSetup() {
    new ScopingStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
