/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.scoping;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Book</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.scoping.scoping.Book#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Book#getImports <em>Imports</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Book#getChapters <em>Chapters</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.scoping.scoping.ScopingPackage#getBook()
 * @model
 * @generated
 */
public interface Book extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getBook_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping.scoping.Book#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping.scoping.DImport}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getBook_Imports()
   * @model containment="true"
   * @generated
   */
  EList<DImport> getImports();

  /**
   * Returns the value of the '<em><b>Chapters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping.scoping.Chapter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chapters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chapters</em>' containment reference list.
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getBook_Chapters()
   * @model containment="true"
   * @generated
   */
  EList<Chapter> getChapters();

} // Book
