/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.scoping;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.scoping.scoping.Chapter#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Chapter#getChapter <em>Chapter</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Chapter#getParagraphs <em>Paragraphs</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Chapter#getReferences <em>References</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.scoping.scoping.ScopingPackage#getChapter()
 * @model
 * @generated
 */
public interface Chapter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getChapter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping.scoping.Chapter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Chapter</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping.scoping.Chapter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Chapter</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chapter</em>' containment reference list.
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getChapter_Chapter()
   * @model containment="true"
   * @generated
   */
  EList<Chapter> getChapter();

  /**
   * Returns the value of the '<em><b>Paragraphs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping.scoping.Paragraph}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paragraphs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragraphs</em>' containment reference list.
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getChapter_Paragraphs()
   * @model containment="true"
   * @generated
   */
  EList<Paragraph> getParagraphs();

  /**
   * Returns the value of the '<em><b>References</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.scoping.scoping.Reference}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>References</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>References</em>' containment reference list.
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getChapter_References()
   * @model containment="true"
   * @generated
   */
  EList<Reference> getReferences();

} // Chapter
