/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.scoping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.scoping.scoping.Reference#getCref <em>Cref</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Reference#getQnref <em>Qnref</em>}</li>
 *   <li>{@link org.xtext.example.scoping.scoping.Reference#getPref <em>Pref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.scoping.scoping.ScopingPackage#getReference()
 * @model
 * @generated
 */
public interface Reference extends EObject
{
  /**
   * Returns the value of the '<em><b>Cref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cref</em>' reference.
   * @see #setCref(Chapter)
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getReference_Cref()
   * @model
   * @generated
   */
  Chapter getCref();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping.scoping.Reference#getCref <em>Cref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cref</em>' reference.
   * @see #getCref()
   * @generated
   */
  void setCref(Chapter value);

  /**
   * Returns the value of the '<em><b>Qnref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qnref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qnref</em>' reference.
   * @see #setQnref(Chapter)
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getReference_Qnref()
   * @model
   * @generated
   */
  Chapter getQnref();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping.scoping.Reference#getQnref <em>Qnref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qnref</em>' reference.
   * @see #getQnref()
   * @generated
   */
  void setQnref(Chapter value);

  /**
   * Returns the value of the '<em><b>Pref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pref</em>' reference.
   * @see #setPref(Paragraph)
   * @see org.xtext.example.scoping.scoping.ScopingPackage#getReference_Pref()
   * @model
   * @generated
   */
  Paragraph getPref();

  /**
   * Sets the value of the '{@link org.xtext.example.scoping.scoping.Reference#getPref <em>Pref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pref</em>' reference.
   * @see #getPref()
   * @generated
   */
  void setPref(Paragraph value);

} // Reference
