/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.scoping.ide.contentassist.antlr.internal.InternalScopingParser;
import org.xtext.example.scoping.services.ScopingGrammarAccess;

public class ScopingParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ScopingGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ScopingGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getChapterAccess().getAlternatives_3(), "rule__Chapter__Alternatives_3");
			builder.put(grammarAccess.getReferenceAccess().getAlternatives_0(), "rule__Reference__Alternatives_0");
			builder.put(grammarAccess.getBookAccess().getGroup(), "rule__Book__Group__0");
			builder.put(grammarAccess.getDImportAccess().getGroup(), "rule__DImport__Group__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getChapterAccess().getGroup(), "rule__Chapter__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_0_0(), "rule__Reference__Group_0_0__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_0_1(), "rule__Reference__Group_0_1__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_0_2(), "rule__Reference__Group_0_2__0");
			builder.put(grammarAccess.getBookAccess().getNameAssignment_1(), "rule__Book__NameAssignment_1");
			builder.put(grammarAccess.getBookAccess().getImportsAssignment_2(), "rule__Book__ImportsAssignment_2");
			builder.put(grammarAccess.getBookAccess().getChaptersAssignment_3(), "rule__Book__ChaptersAssignment_3");
			builder.put(grammarAccess.getDImportAccess().getImportedNamespaceAssignment_1(), "rule__DImport__ImportedNamespaceAssignment_1");
			builder.put(grammarAccess.getChapterAccess().getNameAssignment_1(), "rule__Chapter__NameAssignment_1");
			builder.put(grammarAccess.getChapterAccess().getChapterAssignment_3_0(), "rule__Chapter__ChapterAssignment_3_0");
			builder.put(grammarAccess.getChapterAccess().getParagraphsAssignment_3_1(), "rule__Chapter__ParagraphsAssignment_3_1");
			builder.put(grammarAccess.getChapterAccess().getReferencesAssignment_3_2(), "rule__Chapter__ReferencesAssignment_3_2");
			builder.put(grammarAccess.getParagraphAccess().getNameAssignment(), "rule__Paragraph__NameAssignment");
			builder.put(grammarAccess.getReferenceAccess().getCrefAssignment_0_0_1(), "rule__Reference__CrefAssignment_0_0_1");
			builder.put(grammarAccess.getReferenceAccess().getQnrefAssignment_0_1_1(), "rule__Reference__QnrefAssignment_0_1_1");
			builder.put(grammarAccess.getReferenceAccess().getPrefAssignment_0_2_1(), "rule__Reference__PrefAssignment_0_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ScopingGrammarAccess grammarAccess;

	@Override
	protected InternalScopingParser createParser() {
		InternalScopingParser result = new InternalScopingParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ScopingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScopingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
