/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.scoping.ScopingRuntimeModule;
import org.xtext.example.scoping.ScopingStandaloneSetup;
import org.xtext.example.scoping.ide.ScopingIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ScopingIdeSetup extends ScopingStandaloneSetup {
  @Override
  public Injector createInjector() {
    ScopingRuntimeModule _scopingRuntimeModule = new ScopingRuntimeModule();
    ScopingIdeModule _scopingIdeModule = new ScopingIdeModule();
    return Guice.createInjector(Modules2.mixin(_scopingRuntimeModule, _scopingIdeModule));
  }
}
