/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.ide;

import org.xtext.example.scoping.ide.AbstractScopingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ScopingIdeModule extends AbstractScopingIdeModule {
}
