/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.scoping.ui.AbstractScopingUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ScopingUiModule extends AbstractScopingUiModule {
  public ScopingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
