/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ScopingStandaloneSetup extends ScopingStandaloneSetupGenerated {

	def static void doSetup() {
		new ScopingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
