/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ScopingRuntimeModule extends AbstractScopingRuntimeModule {
}
