/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.scoping.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.xtext.example.scoping.scoping.AbstractScopingScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ScopingScopeProvider extends AbstractScopingScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    final IScope scope = super.getScope(context, reference);
    return scope;
  }
}
